# Save PR review data to as artifact to process in a privileged workflow that is dispatched from this one
name: Received PR review
on: [pull_request_review]
jobs:
  pr_review_submitted:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{contains(github.event_name, 'pull_request_review')}}
    # First save github.context (from the unprivileged workflow) and then pass it through to the privileged action
    # where we have access to repo secrets
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - name: Save context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.context) }}
        run: echo $GITHUB_CONTEXT
      - name: Save event
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
        run: echo $GITHUB_EVENT
      - name: Save PR data
        run: |
          mkdir -p ./pr_data
          echo ${{env.GITHUB_CONTEXT}} > ./pr_data/context.json
          echo ${{env.GITHUB_EVENT}} > ./pr_data/event.json
          echo ${{env.JSON}} > ./pr_data/github.json
      - name: Upload context data
        uses: actions/upload-artifact@v3
        with:
          name: pr-data-to-process
          path: pr_data/
