# Save PR review data to as artifact to process in a privileged workflow that is dispatched from this one
name: Received PR review
on: [pull_request_review]
jobs:
  pr_review_submitted:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: ${{contains(github.event_name, 'pull_request_review')}}
    # First save github.context (from the unprivileged workflow) and then pass it through to the privileged action
    # where we have access to repo secrets
    steps:
      - name: Dump GitHub context and save
        id: github_context_step
        env:
          JSON: ${{ toJSON(github.event) }}
        run: |
          mkdir -p ./pr_data
          echo $JSON > ./pr_data/github.json
      - name: Upload context data
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: pr-data-to-process
          path: pr_data/
